# Generated by Django 3.2.11 on 2022-03-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='owner',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='BK00001', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
