# Generated by Django 3.2.11 on 2022-04-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20220304_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='renting_mode',
            field=models.CharField(choices=[('With Assistance', 'With Assistance'), ('Self Use', 'Self Use')], default='Self Use', max_length=200),
        ),
    ]
