# Generated by Django 3.2.11 on 2022-03-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_partnerdispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdispute',
            name='equipment_id',
            field=models.CharField(default='EQ00001', max_length=10, verbose_name='Product Id'),
            preserve_default=False,
        ),
    ]
