# Generated by Django 3.2.11 on 2022-03-04 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiry', '0003_partnerdispute_equipment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=10)),
                ('cancel_reason', models.PositiveIntegerField(choices=[(10, 'Others'), (20, 'Quality Related'), (30, 'Found a better deal'), (40, 'Owner Related')])),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
