# Generated by Django 3.2.11 on 2022-03-07 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipmentrating_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiry', '0004_cancelform'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ReportEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.PositiveIntegerField(choices=[(10, 'Others'), (20, 'Belongs to another person'), (30, 'Is misleading in any way'), (40, 'harasses or advocates harassment of another person;')])),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
