# Generated by Django 3.2.11 on 2022-03-01 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kex.equipment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment_type', '0001_initial'),
        ('brand', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('equipment_location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('daily_rental', models.IntegerField(default=0)),
                ('hourly_rental', models.IntegerField(default=0)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=kex.equipment.models.upload_location)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=kex.equipment.models.upload_location)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=kex.equipment.models.upload_location)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=kex.equipment.models.upload_location)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=kex.equipment.models.upload_location)),
                ('available_start_time', models.DateField()),
                ('available_end_time', models.DateField()),
                ('model', models.CharField(max_length=200)),
                ('manufacturing_year', models.IntegerField(default=0)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=200)),
                ('Horsepower', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('show_phone_number', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_type.equipmenttype')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
