# Generated by Django 3.2.11 on 2022-02-26 10:28

from django.db import migrations, models
import kex.equipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=kex.equipment.models.upload_location),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=kex.equipment.models.upload_location),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=kex.equipment.models.upload_location),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=kex.equipment.models.upload_location),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to=kex.equipment.models.upload_location),
        ),
    ]
