# Generated by Django 3.2.11 on 2022-03-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='Horsepower',
            new_name='horsepower',
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_id',
            field=models.CharField(default='EQ1', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
