# Generated by Django 3.2.11 on 2022-03-04 16:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0004_equipmentrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentrating',
            unique_together={('user', 'equipment')},
        ),
    ]
