# Generated by Django 3.2.11 on 2022-04-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipmentrating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='delivery_choice',
            field=models.CharField(choices=[('Self', 'Self'), ('Help Centre', 'Help Centre')], default='Self', max_length=200),
        ),
    ]
