# Generated by Django 3.2.11 on 2022-02-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twilio_user_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
