# Generated by Django 3.2.11 on 2022-02-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='UR001', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
