# Generated by Django 3.2.11 on 2022-02-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_sent_at',
        ),
    ]
