# Generated by Django 3.2.11 on 2022-04-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220227_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_card_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='AADHAR CARD number of User'),
        ),
    ]
